### ISSUE TITLE
BuildConfig memory should be configurable. 

### ISSUE THREAD

**Issue by simbo1905** [ocd-scm/ocd-builder#5]
React apps can need a ton of memory to build which can be set as: 

```
spec:
  resources:
    limits:
      memory: 2Gi
```

Currently `memory_limit` is named in the sample values.yaml but it is ignored. It should be implimented.
